@startuml
start
:Solicitar ID y cantidad;
if (¿Existe?) then (Sí)
if (Stock suficiente?) then (Sí)
:Restar stock;
:Incrementar ventas;
if (Stock < 5) then (Sí)
:Mostrar alerta;
endif
:Venta exitosa;
else
:Bloquear venta;
endif
else
:Producto no encontrado;
endif
stop
@enduml